const { contextBridge, ipcRenderer } = require('electron');

const api = {
  getExePath: () => ipcRenderer.invoke('get-exe-path'),
  getUserDataPath: () => ipcRenderer.invoke('get-userdata-path'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  restartApp: () => ipcRenderer.invoke('restart-app'),
  sendRestartInstall: () => ipcRenderer.invoke('restart-app'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  readPreset: (filePath) => ipcRenderer.invoke('read-preset', filePath),
  writePreset: (filePath, updates) => ipcRenderer.invoke('write-preset', filePath, updates),
  getLocalPresets: () => ipcRenderer.invoke('get-local-presets'),
  deleteFile: (fileName) => ipcRenderer.invoke('delete-file', fileName),
  downloadFile: (fileUrl, fileName) => ipcRenderer.invoke('download-file', fileUrl, fileName),
  openCalibrationModel: (modelType, forceOpenWith) => ipcRenderer.invoke('open-calibration-model', modelType, forceOpenWith),
  getShortPath: (targetPath) => ipcRenderer.invoke('get-short-path', targetPath),
  readLocalManifest: () => ipcRenderer.invoke('read-local-manifest'),
  saveLocalManifest: (jsonStr) => ipcRenderer.invoke('save-local-manifest', jsonStr),
  applyHotUpdate: (payload) => ipcRenderer.invoke('apply-hot-update', payload),
  readReleaseInfo: () => ipcRenderer.invoke('read-release-info'),
  saveReleaseInfo: (payload) => ipcRenderer.invoke('save-release-info', payload),
  readReleaseConfig: () => ipcRenderer.invoke('read-release-config'),
  saveReleaseConfigCatalog: (payload) => ipcRenderer.invoke('save-release-config-catalog', payload),
  importReleaseConfigImage: (payload) => ipcRenderer.invoke('import-release-config-image', payload),
  readReleaseConfigPreset: (fileName) => ipcRenderer.invoke('read-release-config-preset', fileName),
  saveReleaseConfigPreset: (payload) => ipcRenderer.invoke('save-release-config-preset', payload),
  runReleaseBuild: (mode) => ipcRenderer.invoke('run-release-build', mode),
  openReleasePath: (target) => ipcRenderer.invoke('open-release-path', target),
  readHomeCatalog: () => ipcRenderer.invoke('read-home-catalog'),
  saveHomeCatalog: (payload) => ipcRenderer.invoke('save-home-catalog', payload),
  resetHomeCatalog: () => ipcRenderer.invoke('reset-home-catalog'),
  importHomeCatalogImage: (payload) => ipcRenderer.invoke('import-home-catalog-image', payload),
  initDefaultPresets: () => ipcRenderer.invoke('init-default-presets'),
  duplicatePreset: (payload) => ipcRenderer.invoke('duplicate-preset', payload),
  copyBundledPreset: (fileName) => ipcRenderer.invoke('copy-bundled-preset', fileName),
  readLocalPresetsManifest: () => ipcRenderer.invoke('read-local-presets-manifest'),
  saveLocalPresetsManifest: (jsonStr) => ipcRenderer.invoke('save-local-presets-manifest', jsonStr),
  readBundledPresetsManifest: () => ipcRenderer.invoke('read-bundled-presets-manifest'),
  listLocalPresetsDetailed: (query) => ipcRenderer.invoke('list-local-presets-detailed', query),
  checkFileExists: (fileName) => ipcRenderer.invoke('check-file-exists', fileName),
  deletePresetFiles: (fileNames) => ipcRenderer.invoke('delete-preset-files', fileNames),
  ensurePresetBackup: (filePath) => ipcRenderer.invoke('ensure-preset-backup', filePath),
  readPresetBackup: (filePath) => ipcRenderer.invoke('read-preset-backup', filePath),
  overwritePreset: (filePath, data) => ipcRenderer.invoke('overwrite-preset', filePath, data),
  renamePresetDisplay: (payload) => ipcRenderer.invoke('rename-preset-display', payload),
  showItemInFolder: (fileName) => ipcRenderer.invoke('show-item-in-folder', fileName),
  writeLog: (message) => ipcRenderer.send('write-log', message),
  exportBugReport: () => ipcRenderer.send('export-bug-report'),
  setNativeTheme: (mode) => ipcRenderer.send('set-native-theme', mode),
  onWriteLog: (callback) => ipcRenderer.on('write-log', callback),
  onExportBugReport: (callback) => ipcRenderer.on('export-bug-report', callback),
  onSetNativeTheme: (callback) => ipcRenderer.on('set-native-theme', callback)
};

contextBridge.exposeInMainWorld('electronAPI', api);
contextBridge.exposeInMainWorld('mkpAPI', api);
